# -*- coding: utf-8 -*-
"""Tech Challenge 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGyuPCHG8uhMeFW6ZHY-KFqVQh_eEI9D

# Importação e análise de dados
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, roc_auc_score
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression

# Configurações globais de plotagem
# %matplotlib inline
sns.set(style='whitegrid')

dados = pd.read_csv('data.csv')
dados.head(5)

dados.info()

"""Aqui podemos ver que não existem dados nulos (com excessão última coluna unnamed: 32, essa todos os dados são nulos) e todos os dados são numéricos (float64), com excessão do diagnóstico que é o que queremos descobrir."""

dados.shape

dados.describe()

"""Vamos remover a coluna Unnamed: 32"""

dados = dados.drop('Unnamed: 32', axis=1)

dados.shape

dados = dados.drop('id', axis=1)

dados.shape

dados.drop('diagnosis', axis=1).corr()

"""Temos 30 colunas para 561 dados, um número alto de colunas para não tantos dados, o que pode causar overfitting. Porém o número de 18x mais linhas que colunas ainda é aceitável, iremos realizar alguns testes para ver se será necessário realizar a redução de dimensionalidade

# Análise gráfica
"""

dados.hist(bins=50, figsize=(40, 30))

categorias = ['B', 'M']
mpl.pyplot.pie(dados['diagnosis'].value_counts(), labels = categorias, autopct = "%.0f%%", explode= (0, 0.1), colors = ("g", "r"))

"""### Análise das Variáveis: Distribuição e Relação com o Diagnóstico

Observando os histogramas gerais e a proporção de diagnósticos, é crucial entender como variáveis específicas se comportam para cada tipo de tumor.
Características relacionadas ao tamanho (como `radius_mean` e `area_mean`) costumam ser indicativos fortes da malignidade. Abaixo, vamos investigar detalhadamente essas variáveis principais comparando tumores benignos e malignos usando Boxplots.
"""

# Selecionando algumas das principais características (médias) para visualização
variaveis_principais = ['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean']

# Configurando a área de plotagem (2 linhas, 2 colunas)
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Definindo um dicionário de cores para inverter a paleta
# Supondo que 'B' era verde e 'M' era vermelho, agora 'B' será vermelho e 'M' será verde
cores_invertidas = {'M': 'red', 'B': 'green'}

# Gerando um boxplot para cada variável principal comparando pelo diagnóstico
for i, var in enumerate(variaveis_principais):
    linha = i // 2
    coluna = i % 2
    # O boxplot ajuda a ver a mediana, os quartis e possíveis outliers (pontos fora da curva)
    sns.boxplot(x='diagnosis', y=var, data=dados, ax=axes[linha, coluna], palette=cores_invertidas, hue='diagnosis', legend=False)
    axes[linha, coluna].set_title(f'Distribuição de {var} por Diagnóstico')
    axes[linha, coluna].set_xlabel('Diagnóstico (B = Benigno, M = Maligno)')
    axes[linha, coluna].set_ylabel(var)

plt.tight_layout()
plt.show()

"""### Interpretação dos Gráficos (Boxplots)

* **Diferença Clara de Tamanho:** Fica evidente que tumores malignos ('M') apresentam distribuições de `radius_mean` (raio), `perimeter_mean` (perímetro) e `area_mean` (área) substancialmente maiores em comparação aos benignos.
* **Textura:** A variável `texture_mean` também mostra que tumores malignos tendem a ter valores maiores, embora as caixas (intervalo interquartil) tenham um pouco mais de sobreposição do que as variáveis de tamanho.
* **Outliers:** Podemos notar alguns pontos muito acima do limite superior em tumores benignos (especialmente na área e raio), mas no geral, a separação linear entre as classes parece ser bastante viável para os nossos modelos preditivos.
"""

correlation_matrix = dados.drop('diagnosis', axis=1).corr().round(2)
fig, ax = mpl.pyplot.subplots(figsize=(30,30))
sns.heatmap(data=correlation_matrix, annot=True, linewidths=.5, ax=ax)

"""### Por que a correlação importa?
Variáveis altamente correlacionadas (como `area_mean` e `radius_mean`) carregam informação redundante. Isso justifica o uso do **PCA** adiante: ao invés de descartar colunas manualmente, o PCA criará novos componentes que capturam a maior parte da variância sem a redundância.

Podemos ver correlações muito próximas a 1, como raio, area e perimetro, isso deixa claro que podemos fazer a redução de dimensionabilidade sem muita perca de informação

# Regressão Logística

Antes de partirmos para modelos baseados em instâncias ou árvores, vamos testar a **Regressão Logística**. É um modelo linear simples, rápido e altamente interpretável que serve como base de comparação para modelos mais complexos.
"""

x = dados.drop('diagnosis', axis=1)
y = dados['diagnosis']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y,random_state=7)
# strafity = y garante que a proporção de benigno e maligno seja mantida

# Criando o Pipeline
pipeline_lr = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('lr', LogisticRegression(max_iter=10000))
])

# Parâmetros para o GridSearch
param_grid_lr = {
    'lr__C': [0.01, 0.1, 1, 10, 100],
    'lr__penalty': ['l1', 'l2'],
    'lr__solver': ['liblinear']
}

# Executando a busca
grid_lr = GridSearchCV(pipeline_lr, param_grid_lr, cv=5, scoring='accuracy')
grid_lr.fit(x_train, y_train)

print(f"Melhores parâmetros LogReg: {grid_lr.best_params_}")
print(f"Melhor acurácia (Validação Cruzada): {grid_lr.best_score_:.4f}")

melhor_lr = grid_lr.best_estimator_
pred_lr = melhor_lr.predict(x_test)

print("Matriz de Confusão (Regressão Logística):")
print(confusion_matrix(y_test, pred_lr))
print(f"\nScore no Teste (LR): {melhor_lr.score(x_test, y_test):.4f}")

"""# KNN"""

scaler = StandardScaler()
scaler.fit(x_train)
x_train_escalonado = scaler.transform(x_train)
x_test_escalonado = scaler.transform(x_test)

error = []
for i in range(1, 10):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train_escalonado, y_train)
    pred_i = knn.predict(x_test_escalonado)
    error.append(np.mean(pred_i != y_test))

mpl.pyplot.figure(figsize=(12, 6))
mpl.pyplot.plot(range(1, 10), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
mpl.pyplot.title('Error Rate K Value')
mpl.pyplot.xlabel('K Value')
mpl.pyplot.ylabel('Mean Error')

# Verificando o modelo para K=5 especificamente
knn_test = KNeighborsClassifier(n_neighbors=5)
knn_test.fit(x_train_escalonado, y_train)
pred_test = knn_test.predict(x_test_escalonado)

print("Matriz de Confusão:")
print(confusion_matrix(y_test, pred_test))
print("\nRelatório de Classificação:")
print(classification_report(y_test, pred_test))

print('Training set score (escalonado): {:.4f}'.format(knn_test.score(x_train_escalonado, y_train)))
print('Test set score (escalonado): {:.4f}'.format(knn_test.score(x_test_escalonado, y_test)))

"""Como os valores são próximos, não houve nem overfitting nem underfitting, e o modelo performou muito bem

### Melhorando o KNN com PCA e GridSearch

Vamos aplicar o PCA para reduzir a correlação entre as variáveis e usar o `GridSearchCV` para encontrar a melhor combinação de parâmetros.
"""

# Criando um Pipeline que primeiro escala, depois reduz a dimensionalidade e por fim aplica o KNN
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)), # Mantém 95% da variância dos dados
    ('knn', KNeighborsClassifier())
])

# Parâmetros para testar no GridSearch
param_grid = {
    'knn__n_neighbors': range(1, 21),
    'knn__weights': ['uniform', 'distance'],
    'knn__metric': ['euclidean', 'manhattan']
}

# Executando a busca pelo melhor modelo
grid = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy')
grid.fit(x_train, y_train)

print(f"Melhores parâmetros: {grid.best_params_}")
print(f"Melhor acurácia na validação cruzada: {grid.best_score_:.4f}")

# Avaliando o melhor modelo encontrado no conjunto de teste
melhor_modelo = grid.best_estimator_
pred_final = melhor_modelo.predict(x_test)

print("Matriz de Confusão (Modelo Otimizado):")
print(confusion_matrix(y_test, pred_final))
print("\nRelatório de Classificação:")
print(classification_report(y_test, pred_final))
print(f"Score final no Teste: {melhor_modelo.score(x_test, y_test):.4f}")

"""### Análise da Redução de Dimensionalidade (PCA)
Vamos verificar para quantas dimensões os dados foram reduzidos e como as colunas originais contribuem para os novos componentes.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Acessando o PCA de dentro do melhor modelo do GridSearch
pca_final = melhor_modelo.named_steps['pca']
n_componentes = pca_final.n_components_

print(f"O PCA reduziu as 30 colunas originais para {n_componentes} componentes principais.")

# Analisando a Variância Explicada
plt.figure(figsize=(10, 5))
plt.bar(range(1, n_componentes + 1), pca_final.explained_variance_ratio_)
plt.xlabel('Componente Principal')
plt.ylabel('Proporção de Variância Explicada')
plt.title('Variância Explicada por cada Componente')
plt.show()

# Criando um DataFrame com os Loadings (pesos das variáveis originais)
features = x.columns
loadings = pd.DataFrame(
    pca_final.components_.T,
    columns=[f'PC{i+1}' for i in range(n_componentes)],
    index=features
)

print("\nContribuição das variáveis originais nos primeiros 5 componentes:")
display(loadings.head())

# Mapa de calor para ver quais variáveis mais influenciam os primeiros componentes
plt.figure(figsize=(12, 8))
sns.heatmap(loadings.iloc[:, :min(5, n_componentes)], cmap='coolwarm', center=0)
plt.title('Influência das Variáveis Originais nos Componentes Principais')
plt.show()

"""### Entendendo a Redução de Dimensionalidade
Aqui aplicamos o PCA mantendo **95% da variância**. Isso significa que, embora tenhamos reduzido de 30 para 10 variáveis, perdemos apenas 5% da 'capacidade explicativa' dos dados originais. Isso ajuda o modelo a focar no sinal (padrões) e ignorar o ruído.

# Comparação com outros modelos: SVM (Support Vector Machine)
O SVM é muito eficaz para problemas de classificação binária em conjuntos de dados com muitas características.
"""

# O SVM também é sensível à escala, então mantemos o StandardScaler
pipeline_svm = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('svm', SVC(probability=True))
])

# Parâmetros para o GridSearch do SVM
param_grid_svm = {
    'svm__C': [0.1, 1, 10, 100],
    'svm__gamma': ['scale', 'auto', 0.1, 0.01],
    'svm__kernel': ['rbf', 'linear', 'poly']
}

# Executando a busca
grid_svm = GridSearchCV(pipeline_svm, param_grid_svm, cv=5, scoring='accuracy')
grid_svm.fit(x_train, y_train)

print(f"Melhores parâmetros SVM: {grid_svm.best_params_}")
print(f"Melhor acurácia (Validação Cruzada): {grid_svm.best_score_:.4f}")

# Avaliação final do SVM
melhor_svm = grid_svm.best_estimator_
pred_svm = melhor_svm.predict(x_test)

print("Matriz de Confusão (SVM):")
print(confusion_matrix(y_test, pred_svm))
print("\nRelatório de Classificação:")
print(classification_report(y_test, pred_svm))
print(f"Score final no Teste: {melhor_svm.score(x_test, y_test):.4f}")

"""### Vantagens do SVM neste Cenário

O modelo **Support Vector Machine (SVM)** demonstrou ser superior para este problema por alguns motivos técnicos:

1.  **Falsos Positivos Zero**: Em diagnósticos médicos, classificar um tumor benigno como maligno (Falso Positivo) pode gerar estresse desnecessário e biópsias invasivas. O SVM alcançou precisão de 100% para a classe Maligna, eliminando esses erros no conjunto de teste.
2.  **Alta Dimensionalidade**: Mesmo após o PCA, o SVM lida muito bem com espaços de características complexos. Ele foca apenas nos pontos mais difíceis de classificar (os vetores de suporte), o que o torna robusto contra ruídos.
3.  **Kernel Linear**: O fato do melhor modelo ter usado um kernel linear indica que os dados, quando escalonados e reduzidos pelo PCA, tornam-se linearmente separáveis com facilidade, permitindo um modelo mais simples e com menor risco de overfitting.

# Comparação com Random Forest
O Random Forest é um conjunto de árvores de decisão. É robusto a outliers e não assume uma distribuição linear dos dados.
"""

# Criando o Pipeline para Random Forest
pipeline_rf = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('rf', RandomForestClassifier(random_state=7))
])

# Parâmetros para o GridSearch do Random Forest
param_grid_rf = {
    'rf__n_estimators': [50, 100, 200],
    'rf__max_depth': [None, 10, 20],
    'rf__min_samples_split': [2, 5],
    'rf__criterion': ['gini', 'entropy']
}

# Executando a busca
grid_rf = GridSearchCV(pipeline_rf, param_grid_rf, cv=5, scoring='accuracy')
grid_rf.fit(x_train, y_train)

print(f"Melhores parâmetros RF: {grid_rf.best_params_}")
print(f"Melhor acurácia (Validação Cruzada): {grid_rf.best_score_:.4f}")

# Avaliação final do Random Forest
melhor_rf = grid_rf.best_estimator_
pred_rf = melhor_rf.predict(x_test)

print("Matriz de Confusão (Random Forest):")
print(confusion_matrix(y_test, pred_rf))
print("\nRelatório de Classificação:")
print(classification_report(y_test, pred_rf))
print(f"Score final no Teste (RF): {melhor_rf.score(x_test, y_test):.4f}")
print(f"Score final no Teste (SVM anterior): {melhor_svm.score(x_test, y_test):.4f}")

"""### Análise de Desempenho e Erros

Ao analisarmos os resultados detalhados, observamos por que o **SVM** superou o **Random Forest** neste cenário:

*   **Acurácia e Generalização**: O Random Forest atingiu uma acurácia de **93.86%**, enquanto o SVM alcançou **96.49%**. Isso indica que o SVM conseguiu criar uma fronteira de separação mais eficiente para este conjunto de dados após a redução de dimensionalidade.
*   **Falsos Positivos (FP)**: O Random Forest apresentou **2 falsos positivos** (casos benignos classificados como malignos). Embora baixo, o SVM zerou essa métrica, o que evita alarmes falsos e procedimentos desnecessários.
*   **Falsos Negativos (FN)**: Este é o erro mais crítico na medicina. O Random Forest deixou passar **5 casos malignos**, classificando-os como benignos. O SVM reduziu esse número para **4 casos**.
*   **Veredito**: O SVM mostrou-se mais robusto, oferecendo maior segurança no diagnóstico ao minimizar ambos os tipos de erro, especialmente os Falsos Positivos, mantendo uma sensibilidade superior.

# Implementação do XGBoost
O XGBoost é um algoritmo de boosting de gradiente que costuma oferecer alta performance em dados tabulares.
"""

# O XGBoost requer que as classes sejam numéricas
le = LabelEncoder()
y_train_num = le.fit_transform(y_train)
y_test_num = le.transform(y_test)

# Criando o Pipeline para XGBoost
pipeline_xgb = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('xgb', XGBClassifier(random_state=7, eval_metric='logloss'))
])

# Parâmetros para o GridSearch do XGBoost
param_grid_xgb = {
    'xgb__n_estimators': [50, 100, 200],
    'xgb__learning_rate': [0.01, 0.1, 0.2],
    'xgb__max_depth': [3, 5, 7],
    'xgb__subsample': [0.8, 1.0]
}

# Executando a busca
grid_xgb = GridSearchCV(pipeline_xgb, param_grid_xgb, cv=5, scoring='accuracy')
grid_xgb.fit(x_train, y_train_num)

print(f"Melhores parâmetros XGBoost: {grid_xgb.best_params_}")

# Avaliação final do XGBoost
melhor_xgb = grid_xgb.best_estimator_
pred_xgb_num = melhor_xgb.predict(x_test)

print("Matriz de Confusão (XGBoost):")
print(confusion_matrix(y_test_num, pred_xgb_num))
print("\nRelatório de Classificação:")
print(classification_report(y_test_num, pred_xgb_num, target_names=le.classes_))
print(f"Score final no Teste (XGBoost): {melhor_xgb.score(x_test, y_test_num):.4f}")
print(f"Score final no Teste (SVM anterior): {melhor_svm.score(x_test, y_test):.4f}")

"""### Conclusão Final: SVM vs XGBoost

Ambos os modelos atingiram o topo do desempenho neste conjunto de dados:

*   **Performance Idêntica**: Ambos obtiveram **96,49%** de acurácia no teste.
*   **Seguran'ca no Diagnóstico**: Tanto o SVM quanto o XGBoost apresentaram **zero Falsos Positivos**, garantindo que nenhum paciente saudável fosse classificado erroneamente como portador de tumor maligno.
*   **Sensibilidade**: Ambos tiveram apenas 4 falsos negativos em 114 amostras.

**Escolha do Modelo**: O **SVM (Linear)** é ligeiramente preferível aqui por ser um modelo mais simples (menos hiperparâmetros) e computacionalmente mais leve para este volume de dados, mantendo a mesma eficácia do XGBoost.

### Comparação Gráfica: SVM vs XGBoost

Nesta seção, geramos as curvas ROC (Receiver Operating Characteristic) e calculamos a AUC (Area Under the Curve). A AUC mede a capacidade do modelo de distinguir entre as classes. Além disso, comparamos os resultados da validação cruzada (K-fold).
"""

# Obtendo as probabilidades de predição para comparação de performance
y_score_svm = melhor_svm.predict_proba(x_test)[:, 1]
y_score_xgb = melhor_xgb.predict_proba(x_test)[:, 1]
y_score_lr = melhor_lr.predict_proba(x_test)[:, 1]

# Calculando as curvas ROC
fpr_svm, tpr_svm, _ = roc_curve(y_test_num, y_score_svm)
roc_auc_svm = auc(fpr_svm, tpr_svm)

fpr_xgb, tpr_xgb, _ = roc_curve(y_test_num, y_score_xgb)
roc_auc_xgb = auc(fpr_xgb, tpr_xgb)

fpr_lr, tpr_lr, _ = roc_curve(y_test_num, y_score_lr)
roc_auc_lr = auc(fpr_lr, tpr_lr)

# Plotagem comparativa
plt.figure(figsize=(10, 6))
plt.plot(fpr_svm, tpr_svm, color='blue', lw=2, label=f'ROC SVM (AUC = {roc_auc_svm:.4f})')
plt.plot(fpr_xgb, tpr_xgb, color='green', lw=2, label=f'ROC XGBoost (AUC = {roc_auc_xgb:.4f})')
plt.plot(fpr_lr, tpr_lr, color='red', lw=2, linestyle='--', label=f'ROC LogReg (AUC = {roc_auc_lr:.4f})')
plt.plot([0, 1], [0, 1], color='gray', lw=1, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Taxa de Falsos Positivos (FPR)')
plt.ylabel('Taxa de Verdadeiros Positivos (TPR)')
plt.title('Curvas ROC - Comparação Final de Modelos')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

# Atualizando o gráfico ROC para incluir Regressão Logística
y_score_lr = melhor_lr.predict_proba(x_test)[:, 1]
fpr_lr, tpr_lr, _ = roc_curve(y_test_num, y_score_lr)
roc_auc_lr = auc(fpr_lr, tpr_lr)

plt.figure(figsize=(10, 6))
plt.plot(fpr_svm, tpr_svm, color='blue', lw=2, label=f'ROC SVM (AUC = {roc_auc_svm:.4f})')
plt.plot(fpr_xgb, tpr_xgb, color='green', lw=2, label=f'ROC XGBoost (AUC = {roc_auc_xgb:.4f})')
plt.plot(fpr_lr, tpr_lr, color='red', lw=2, linestyle='--', label=f'ROC LogReg (AUC = {roc_auc_lr:.4f})')
plt.plot([0, 1], [0, 1], color='gray', lw=1, linestyle='--')
plt.title('Curvas ROC - Comparação Incluindo LogReg')
plt.legend(loc="lower right")
plt.show()

# Gráfico de barras comparando Validação Cruzada (K-Fold) e Acurácia de Teste
modelos = ['SVM', 'XGBoost']
cv_scores = [grid_svm.best_score_, grid_xgb.best_score_]
test_scores = [melhor_svm.score(x_test, y_test), melhor_xgb.score(x_test, y_test_num)]

x_axis = np.arange(len(modelos))

plt.figure(figsize=(10, 6))
plt.bar(x_axis - 0.2, cv_scores, 0.4, label='Melhor Score CV (5-fold)', color='skyblue')
plt.bar(x_axis + 0.2, test_scores, 0.4, label='Acurácia no Teste', color='orange')

plt.xticks(x_axis, modelos)
plt.ylabel("Acurácia")
plt.title("Comparação de Performance: K-Fold CV vs Teste")
plt.legend(loc='lower center')
plt.ylim(0.9, 1.0)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Atualizando comparação de barras
modelos_ext = ['LogReg', 'SVM', 'XGBoost']
cv_scores_ext = [grid_lr.best_score_, grid_svm.best_score_, grid_xgb.best_score_]
test_scores_ext = [melhor_lr.score(x_test, y_test), melhor_svm.score(x_test, y_test), melhor_xgb.score(x_test, y_test_num)]

x_axis_ext = np.arange(len(modelos_ext))

plt.figure(figsize=(12, 6))
plt.bar(x_axis_ext - 0.2, cv_scores_ext, 0.4, label='Melhor Score CV (5-fold)', color='skyblue')
plt.bar(x_axis_ext + 0.2, test_scores_ext, 0.4, label='Acurácia no Teste', color='orange')

plt.xticks(x_axis_ext, modelos_ext)
plt.title("Comparação de Performance Final")
plt.legend()
plt.ylim(0.9, 1.0)
plt.show()

"""### Análise de Casos Críticos (Falsos Negativos)
Em um contexto médico, o custo de um **Falso Negativo** (dizer que um tumor é benigno quando é maligno) é muito maior que um Falso Positivo. Vamos identificar quem são esses casos que o SVM/XGBoost não conseguiram prever.
"""

import numpy as np
# Identificando os índices onde o SVM errou
erros_idx = np.where(y_test != pred_svm)[0]
dados_erros = x_test.iloc[erros_idx].copy()
dados_erros['Real'] = y_test.iloc[erros_idx].values
dados_erros['Previsto'] = pred_svm[erros_idx]

print("Amostras que o modelo não conseguiu classificar corretamente:")
display(dados_erros[['Real', 'Previsto']])

"""### Análise Detalhada: ROC/AUC e Validação Cruzada

A comparação visual e estatística entre o **SVM** e o **XGBoost** nos permite extrair conclusões sólidas sobre a confiabilidade do diagnóstico:

1.  **Curva ROC e AUC**: Ambos os modelos atingiram uma **AUC de aproximadamente 0.994**. Isso significa que há uma probabilidade de 99,4% de que o modelo classifique corretamente um caso maligno escolhido aleatoriamente acima de um caso benigno. As curvas estão quase encostadas no canto superior esquerdo, o que representa um classificador quase perfeito.
2.  **Validação Cruzada (K-Fold)**: Como utilizamos `cv=5` no `GridSearchCV`, os modelos foram treinados e validados 5 vezes em subconjuntos diferentes dos dados. O fato do **Score de Validação (CV)** ser muito próximo da **Acurácia de Teste** (como visto no gráfico de barras) prova que o modelo é estável e não está apenas "decorando" os dados de treino (overfitting).
3.  **Confiabilidade**: O empate técnico em 96,49% de acurácia no teste, somado ao fato de ambos terem **zero falsos positivos**, indica que qualquer uma dessas escolhas é estatisticamente segura. O SVM leva uma pequena vantagem por ser mais simples de interpretar e processar para este volume de dados específico.

# Conclusão Geral do Projeto

1. **Processamento**: A escala (`StandardScaler`) foi fundamental, pois modelos como KNN e SVM baseiam-se em distâncias.
2. **Modelagem**: O **SVM** e o **XGBoost** empataram em performance, mas o SVM linear é preferível pela simplicidade (Navalha de Ockham).
3. **Métricas**: A acurácia de **96.5%** é excelente, mas o destaque é a **Precisão de 100%** para a classe Maligna, garantindo segurança contra falsos alarmes.
4. **Próximos Passos**: Para reduzir os 4 Falsos Negativos restantes, poderíamos investigar técnicas de *Ensemble* mais complexas ou coletar mais dados de casos limítrofes.

## Teste Comparativo: MinMaxScaler vs StandardScaler

Agora vamos testar se a normalização dos dados entre 0 e 1 (`MinMaxScaler`) melhora a performance do KNN e do SVM em relação à padronização anterior (`StandardScaler`).
"""

from sklearn.preprocessing import MinMaxScaler

# 1. Testando KNN com MinMaxScaler
pipeline_knn_mm = Pipeline([
    ('scaler', MinMaxScaler()),
    ('pca', PCA(n_components=0.95)),
    ('knn', KNeighborsClassifier())
])

grid_knn_mm = GridSearchCV(pipeline_knn_mm, param_grid, cv=5, scoring='accuracy')
grid_knn_mm.fit(x_train, y_train)

# 2. Testando SVM com MinMaxScaler
pipeline_svm_mm = Pipeline([
    ('scaler', MinMaxScaler()),
    ('pca', PCA(n_components=0.95)),
    ('svm', SVC(probability=True))
])

grid_svm_mm = GridSearchCV(pipeline_svm_mm, param_grid_svm, cv=5, scoring='accuracy')
grid_svm_mm.fit(x_train, y_train)

print(f"KNN (MinMax) - Melhor Score CV: {grid_knn_mm.best_score_:.4f}")
print(f"SVM (MinMax) - Melhor Score CV: {grid_svm_mm.best_score_:.4f}")

# Comparação Final no Teste
score_knn_mm = grid_knn_mm.best_estimator_.score(x_test, y_test)
score_svm_mm = grid_svm_mm.best_estimator_.score(x_test, y_test)

print(f"Acurácia Final Teste (KNN + MinMax): {score_knn_mm:.4f}")
print(f"Acurácia Final Teste (SVM + MinMax): {score_svm_mm:.4f}")
print(f"\n(Para referência) Acurácia Anterior (SVM + StandardScaler): {melhor_svm.score(x_test, y_test):.4f}")

"""### Visualização da Matriz de Confusão Final

Para encerrar a análise, vamos visualizar a matriz de confusão do melhor modelo (SVM) de forma gráfica. Esta representação facilita a identificação imediata do erro do tipo II (Falsos Negativos).
"""

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Calculando a matriz com o melhor estimador do SVM
cm = confusion_matrix(y_test, pred_svm)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benigno', 'Maligno'],
            yticklabels=['Benigno', 'Maligno'])

plt.title('Matriz de Confusão - Melhor SVM')
plt.ylabel('Realidade')
plt.xlabel('Predição')
plt.show()

"""## Otimização para Diagnóstico Médico: Minimizando Falsos Negativos

Em diagnósticos de câncer, um **Falso Negativo** (não detectar a doença) é consideravelmente mais perigoso que um Falso Positivo. Para mitigar isso, vamos ajustar o modelo SVM para priorizar a sensibilidade (*recall*) da classe Maligna, utilizando pesos de classe diferenciados.
"""

# Ajustando o SVM com pesos para penalizar Falsos Negativos
# Atribuímos peso 5 para 'Maligno' e 1 para 'Benigno'
pesos_classe = {'B': 1, 'M': 5}

pipeline_sensivel = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('svm', SVC(kernel='linear', class_weight=pesos_classe, probability=True, random_state=7))
])

# Treinando o modelo focado em sensibilidade
pipeline_sensivel.fit(x_train, y_train)
pred_sensivel = pipeline_sensivel.predict(x_test)

# Resultados
print("Matriz de Confusão (Foco em Falsos Negativos):")
cm_sensivel = confusion_matrix(y_test, pred_sensivel)
display(sns.heatmap(cm_sensivel, annot=True, fmt='d', cmap='Reds', xticklabels=['B', 'M'], yticklabels=['B', 'M']))
plt.show()

print("\nRelatório de Classificação:")
print(classification_report(y_test, pred_sensivel))

# Comparação direta
fn_anterior = cm[1, 0]
fn_novo = cm_sensivel[1, 0]
print(f"Falsos Negativos Anteriores: {fn_anterior}")
print(f"Falsos Negativos Atuais: {fn_novo}")

"""### Conclusão: Otimização de Sensibilidade (SVM)

Nesta etapa final, priorizamos a segurança do paciente ao ajustar o modelo SVM para ser mais rigoroso com a detecção de tumores malignos:

1. **Redução de Erros Críticos**: Ao ajustar o `class_weight` para 5, conseguimos diminuir os **Falsos Negativos de 4 para 2**. Isso significa que metade dos erros fatais do modelo original foram eliminados.
2. **Equilíbrio de Performance**: A acurácia geral permaneceu robusta em **96.49%**, provando que o ajuste foi cirúrgico e não prejudicou o modelo como um todo.
3. **Custo-Benefício**: Houve a geração de apenas 2 Falsos Positivos. Em um contexto médico, o custo de realizar exames complementares em 2 pacientes saudáveis é negligenciável comparado ao benefício de detectar 2 tumores malignos que seriam ignorados.

Este modelo SVM otimizado oferece um excelente equilíbrio entre precisão e segurança clínica.

## Otimização do XGBoost para Diagnóstico Médico

Assim como no SVM, podemos ajustar o XGBoost para ser mais sensível à classe Maligna. No XGBoost, usamos o parâmetro `scale_pos_weight`, que é a razão entre o número de amostras negativas e positivas (ou um valor arbitrário para aumentar a importância da classe positiva).
"""

# Calculando o peso ideal ou definindo um peso manual (ex: 2)
# scale_pos_weight = sum(negative cases) / sum(positive cases)

pipeline_xgb_sensivel = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('xgb', XGBClassifier(n_estimators=100, learning_rate=0.2, max_depth=3,
                           scale_pos_weight=100, eval_metric='logloss', random_state=7))
])

# Treinando o XGBoost sensível
pipeline_xgb_sensivel.fit(x_train, y_train_num)
pred_xgb_sensivel = pipeline_xgb_sensivel.predict(x_test)

# Resultados XGBoost
cm_xgb_sensivel = confusion_matrix(y_test_num, pred_xgb_sensivel)

print("Matriz de Confusão (XGBoost com Peso):")
display(sns.heatmap(cm_xgb_sensivel, annot=True, fmt='d', cmap='Oranges',
                    xticklabels=le.classes_, yticklabels=le.classes_))
plt.show()

print(f"\nFalsos Negativos (SVM Sensível): {cm_sensivel[1, 0]}")
print(f"Falsos Negativos (XGBoost Sensível): {cm_xgb_sensivel[1, 0]}")
print(f"Acurácia Final XGBoost Sensível: {pipeline_xgb_sensivel.score(x_test, y_test_num):.4f}")

"""### Comparativo Final de Modelos Otimizados

Ao final desta análise, comparamos as versões dos modelos configuradas especificamente para evitar o erro mais caro no diagnóstico (Falsos Negativos):

*   **SVM Sensível (Peso 5)**: **2 Falsos Negativos** | 2 Falsos Positivos | Acurácia 96.49%
*   **XGBoost Sensível (Peso 100)**: **1 Falso Negativo** | 3 Falsos Positivos | Acurácia 96.49%

**Conclusão**: O ajuste de pesos provou ser a técnica mais poderosa para customizar a segurança do diagnóstico. O **XGBoost (Peso 100)** oferece a proteção máxima contra omissões de diagnóstico (apenas 1 erro), enquanto o **SVM (Peso 5)** apresenta um equilíbrio notável com apenas 2 erros de cada tipo. Ambos os modelos são superiores à configuração padrão para uso em triagem médica.

### Estratégia de Alta Sensibilidade (Aggressive Weighting)

Ao elevar o `scale_pos_weight` para 100 no XGBoost, forçamos o modelo a um estado de **vigilância máxima**.

*   **Impacto Clínico**: Reduzir os Falsos Negativos para apenas 1 é um marco importante. Em cenários de triagem, preferimos investigar 3 casos saudáveis a mais (Falsos Positivos) do que permitir que um paciente com a doença receba um diagnóstico falso de saúde.
*   **Trade-off**: Note que a precisão da classe Maligna caiu levemente (surgiram 3 Falsos Positivos), mas a **Sensibilidade (Recall)** subiu para quase 98%.
*   **Veredito**: Se o objetivo é a segurança absoluta do paciente, esta configuração do XGBoost torna-se a candidata principal para o deploy.

### Veredito Final sobre Sensibilidade

Ao aplicar pesos de classe tanto no SVM quanto no XGBoost, observamos se um dos modelos consegue errar ainda menos na detecção de tumores malignos. Geralmente, o SVM Linear mantém uma fronteira mais estável em conjuntos pequenos, mas o XGBoost oferece flexibilidade para capturar nuances se o peso for bem ajustado.
"""